version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/docker/nginx/logs:/var/log/nginx
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  default:
    external:
      name: development