version: '3.6'

services:
  jenkins:
    image: jenkinsci/blueocean:latest
    ports:
      - "50000:50000"
      - "8081:8080"
    volumes:
      - /opt/docker/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  default:
    external:
      name: development